[workspace]
resolver = "3"
members = ["crates/*"]

[workspace.package]
version = "0.0.0"
edition = "2024"
rust-version = "1.85"
license = "MIT"
repository = "https://github.com/orin-axi/monokl"
authors = ["Orin-Axi Contributors"]
keywords = ["orin-axi", "developer-tools"]
categories = ["development-tools"]
publish = false
